org:
  repositories:
    ci_travis_xtuple: xtuple/xtuple
    ci_travis_xtuple_extensions: xtuple/xtuple-extensions
  type: org
pro:
  repositories:
    ci_travis_xtuple_private_extensions: xtuple/private-extensions
  type: pro
